name: "Download fake relay"
description: "Download fake relay for integration tests"
runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Clone remote repository
      shell: bash
      run: |
        git clone https://github.com/ZanCorDX/fake-relay.git

    - name: Build
      shell: bash
      run: |
        cd fake-relay
        go build -v -o mev-boost-fake-relay .
        echo "$PWD" >> $GITHUB_PATH
